
package controllers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITaskService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITaskService {


    /**
     * 
     * @return
     *     returns ArrayOfint
     */
    @WebMethod(operationName = "GetCustomersIds", action = "http://tempuri.org/ITaskService/GetCustomersIds")
    @WebResult(name = "GetCustomersIdsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomersIds", targetNamespace = "http://tempuri.org/", className = "controllers.GetCustomersIds")
    @ResponseWrapper(localName = "GetCustomersIdsResponse", targetNamespace = "http://tempuri.org/", className = "controllers.GetCustomersIdsResponse")
    public ArrayOfint getCustomersIds();

    /**
     * 
     * @param id
     * @return
     *     returns Customer
     */
    @WebMethod(operationName = "GetCustomerData", action = "http://tempuri.org/ITaskService/GetCustomerData")
    @WebResult(name = "GetCustomerDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerData", targetNamespace = "http://tempuri.org/", className = "controllers.GetCustomerData")
    @ResponseWrapper(localName = "GetCustomerDataResponse", targetNamespace = "http://tempuri.org/", className = "controllers.GetCustomerDataResponse")
    public Customer getCustomerData(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

}
