
package controllers;

import play.db.ebean.Model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.persistence.Entity;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://193.142.112.220:90/taskservice/taskservice.svc?wsdl")
public class TaskService
    extends Service {

    private final static URL TASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKSERVICE_EXCEPTION;
    private final static QName TASKSERVICE_QNAME = new QName("http://tempuri.org/", "TaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://193.142.112.220:90/taskservice/taskservice.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKSERVICE_WSDL_LOCATION = url;
        TASKSERVICE_EXCEPTION = e;
    }

    public TaskService() {
        super(__getWsdlLocation(), TASKSERVICE_QNAME);
    }

    public TaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKSERVICE_QNAME, features);
    }

    public TaskService(URL wsdlLocation) {
        super(wsdlLocation, TASKSERVICE_QNAME);
    }

    public TaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKSERVICE_QNAME, features);
    }

    public TaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ITaskService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITaskService")
    public ITaskService getBasicHttpBindingITaskService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITaskService"), ITaskService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ITaskService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITaskService")
    public ITaskService getBasicHttpBindingITaskService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITaskService"), ITaskService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKSERVICE_EXCEPTION != null) {
            throw TASKSERVICE_EXCEPTION;
        }
        return TASKSERVICE_WSDL_LOCATION;
    }
}

